import ChatBody from "@/components/ChatBody";
import Header from "@/components/Header";
import Input from "@/components/Input";
import Head from "next/head";
import { getProviders, getSession, useSession } from "next-auth/react";
import { DocumentContext } from "next/document";

export default function Home() {
  const { data: session } = useSession();

  if (!session) <Header />;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main className="text-[#8696a0] max-w-3xl mx-auto">
        <ChatBody />
        <Input />
      </main>
    </>
  );
}

export async function getServerSideProps(context: DocumentContext) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}
