import ChatBody from "@/components/ChatBody";
import Header from "@/components/Header";
import Input from "@/components/Input";
import Head from "next/head";
import { getProviders, getSession, useSession } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Chat App generated by next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main className="mx-auto max-w-3xl text-[#8696a0]">
        <ChatBody />
        <Input />
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      providers,
      session,
    },
  };
}
